<templateSet group="JavaScript">
  <template name="rest:try" value="try{&#10;    $END$&#10;    res.status(200).send({&#10;        success: true&#10;    })&#10;}catch(e){&#10;    helper.internalError(e.message, res);&#10;}" description="Try catch for rest server" toReformat="true" toShortenFQNames="true">
    <context>
      <option name="JAVA_SCRIPT" value="true" />
    </context>
  </template>
  <template name="rest:f" value="async $FUNC$(req, res) {&#10;    try{&#10;        $END$&#10;        return res.status(200).send({&#10;            success: true,&#10;            data: null&#10;        })&#10;    }catch(e){&#10;        return helper.internalError(e.message, res);&#10;    }&#10;}" description="Restfull function" toReformat="true" toShortenFQNames="true">
    <variable name="FUNC" expression="" defaultValue="rest" alwaysStopAt="true" />
    <context>
      <option name="JAVA_SCRIPT" value="true" />
    </context>
  </template>
  <template name="ts:f" value="async $FUNC$(req: Request, res: Response) {&#10;        try {&#10;            $END$&#10;        }&#10;        catch (e) {&#10;            return helper.error(res, {&#10;                code: 500,&#10;                message: 'Server internal error',&#10;                error: e&#10;            });&#10;        }&#10;    }" description="Typescript Resful function" toReformat="true" toShortenFQNames="true">
    <variable name="FUNC" expression="" defaultValue="" alwaysStopAt="true" />
    <context>
      <option name="TypeScript" value="true" />
    </context>
  </template>
</templateSet>